services:
  backend:
    image: arpits15/proxima-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}

  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
