spring.application.name=demo

jwt.secretKey=${JWT_SECRET_KEY:ofigicjkadgyegfouiasdgf8wtf9asdgwetfp9ewfgidgsugwp7eft87egdpiw9e7ftpgousyfgwe97fte7g8FTWEP9FGLI8FT7Fgol7ge}

# PostgreSQL Configuration
spring.datasource.url=${JDBC_URL}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

uploadcare.publicKey=${UPLOAD_CARE_PUBLIC_KEY}
uploadcare.secretKey=${UPLOAD_CARE_SECRET_KEY}

# Kafka Configuration
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP_ID:proxima-chat-group}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.properties.security.protocol=${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
spring.kafka.properties.sasl.mechanism=${KAFKA_SASL_MECHANISM:}
spring.kafka.properties.sasl.jaas.config=${KAFKA_SASL_JAAS_CONFIG:}


spring.kafka.properties.ssl.endpoint.identification.algorithm=${KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM:https}
spring.kafka.properties.ssl.protocol=${KAFKA_SSL_PROTOCOL:TLS}


spring.mail.username=${MAIL_SERVICE_EMAIL}
spring.mail.password=${MAIL_SERVICE_PASSWORD}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Redis Configuration
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.username=${REDIS_USERNAME}
spring.data.redis.password=${REDIS_PASSWORD}

# Gemini API Configuration
gemini.api.url=${GEMINI_API_URL}
gemini.api.key=${GEMINI_API_KEY}
