spring.application.name=demo

jwt.secretKey=${JWT_SECRET_KEY:ofigicjkadgyegfouiasdgf8wtf9asdgwetfp9ewfgidgsugwp7eft87egdpiw9e7ftpgousyfgwe97fte7g8FTWEP9FGLI8FT7Fgol7ge}

# PostgreSQL Configuration
spring.datasource.url=${JDBC_URL}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

uploadcare.publicKey=${UPLOAD_CARE_PUBLIC_KEY}
uploadcare.secretKey=${UPLOAD_CARE_SECRET_KEY}
